[ALPS08631203] Revert "ANDROID: gki: enable Rust"
[Description]
This reverts commit 8a5fc4f4634539f26d75e7f89e955e2fa0980cac.
This is a workaround for user mode build error:
ERROR: savedefconfig does not match kernel-6.12/arch/arm64/
configs/gki_defconfig

[Test]
boot pass

Signed-off-by: swintegrator <swintegrator@mediatek.com>
Signed-off-by: Clive Lin <clive.lin@mediatek.com>
CR-Id: ALPS08631203
Feature: Kernel SI Operation
Change-Id: I4604d9d2996c7c9fd8b524b5a4feed8401191db5