[ALPS08631203] Revert "ANDROID: GKI: Reduce vendor data in task_struct"
[Description]
This reverts commit 5af1e8b6659893b96af4fc63400e0ebad6476557.
This is a workaround for build error:
kernel_device_modules-6.12/drivers/misc/mediatek/sched/eas/sched_main.c:1000:2: error: call to '__compiletime_assert_1032' declared with 'error' attribute: BUILD_BUG_ON failed: sizeof(struct mtk_task) > (sizeof(u64) * ARRAY_SIZE(((struct task_struct *)0)->android_vendor_data1))
 1000 |         MTK_VENDOR_DATA_SIZE_TEST(struct mtk_task, struct task_struct);
      |         ^

[Test]
boot pass

Signed-off-by: swintegrator <swintegrator@mediatek.com>
Signed-off-by: Clive Lin <clive.lin@mediatek.com>
CR-Id: ALPS08631203
Feature: Kernel SI Operation
Change-Id: If4e922d553d7e97956ae8cb671bec7f7a9d2f1ef